name       : virtualenv-clone
version    : 0.5.4
release    : 5
source     :
    - https://pypi.io/packages/source/v/virtualenv-clone/virtualenv-clone-0.5.4.tar.gz : 665e48dd54c84b98b71a657acb49104c54e7652bce9c1c4f6c6976ed4c827a29
license    : MIT
component  : programming.python
summary    : virtualenv-clone is a script for cloning a non-relocatable virtualenv
description: |
    virtualenv-clone provides a way to make virtualenv's relocatable which could then be copied as we wanted
builddeps  :
    # For tests only
    - python-pytest
    - python-tox
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    sed -i -e '$a[tox:tox]' setup.cfg
    %python3_test
