name       : virtualenv-clone
version    : 0.5.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/af/69/4bf2faa88f0f158bfcc8d66e270e8dafdda92e22f374cf111bde93924b17/virtualenv-clone-0.5.1.tar.gz : 217bd3f0880c9f85672c0bcc9ad9e0354ab7dfa89c2f117e63aa878b4279f5bf
license    : MIT
component  : programming.python
summary    : virtualenv-clone is a script for cloning a non-relocatable virtualenv
description: |
    virtualenv-clone provides a way to make virtualenv's relocatable which could then be copied as we wanted
builddeps  :
    # For tests only
    - python-pytest
    - python-tox
rundeps    :
    - python3
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
