name       : virtualenv-clone
version    : 0.5.3
release    : 4
source     :
    - https://files.pythonhosted.org/packages/d7/a7/08b88808c409722361459f1ae24474530d83593d6ded346f1d3649326838/virtualenv-clone-0.5.3.tar.gz : c88ae171a11b087ea2513f260cdac9232461d8e9369bcd1dc143fc399d220557
license    : MIT
component  : programming.python
summary    : virtualenv-clone is a script for cloning a non-relocatable virtualenv
description: |
    virtualenv-clone provides a way to make virtualenv's relocatable which could then be copied as we wanted
builddeps  :
    # For tests only
    - python-pytest
    - python-tox
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
